apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: composio
spec:
  title: Composio
  icon: "https://avatars.githubusercontent.com/u/128464815?s=48&v=4"
  statusInformers:
    - composio/deployment/composio-apollo
    - composio/deployment/composio-thermos
  additionalNamespaces:
    - composio